name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -covermode=count -coverprofile=coverage.out -v ./...
      
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@e156083f13aff6830c92fc5faa23505779fbf649
      uses: codecov/codecov-action@v1.2.1
  
  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    
    steps:
    - name: Build
      run: ./build && ./upx_compress.sh

    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3

